version: 2
jobs:
  build:
    docker:
      - image: quay.io/cybozu/golang:1.11-bionic
    steps:
      - checkout
      - run: go get -d -v .
      - run: make
      - run: test -z "$(gofmt -s -d . | tee /dev/stderr)"
      - run: go vet ./...
      - run: golint -set_exit_status ./...
      - run: go test -race -v ./...
