# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
        # Shell is non-interactive.  Be done now!
        return
fi


# Put your fun stuff here.
app_pod_uuid() {
    sudo rkt list --format json 2>/dev/null | jq -r '.[] | select(.app_names[0] == "'$1'" and .state == "running") | .name' 2>/dev/null
}

birdc() {
    local uuid
    uuid=$(app_pod_uuid bird)
    if [ "$uuid" = "" ]; then
        echo "bird is not running." 1>&2
        return 1
    fi
    sudo rkt enter --app=bird $uuid birdc "$@"
}

debug() {
    local uuid app
    if [ $# -eq 0 ]; then
        echo "Usage: debug app_name [command] [args...]" 1>&2
        return 1
    fi
    app=$1
    shift
    uuid=$(app_pod_uuid $app)
    if [ "$uuid" = "" ]; then
        echo "$app is not running." 1>&2
        return 1
    fi
    sudo rkt enter --app=ubuntu-debug $uuid "$@"
}
